name: Sync to Seuchico
on:
  push:
    branches:
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        run: |
          git config --global user.email "pedronascimento@exemplo.com"
          git config --global user.name "Pedro Nascimento"
          git remote add mirror https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/seuchicoprojetos-sys/seuchicobotequim-cardapio.git
          git push --force mirror master