name: Sync to Seuchico
on:
  push:
    branches:
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # <--- ISSO IMPEDE O USO DO BOT PADRÃO

      - name: Push to mirror
        run: |
          git remote add mirror https://${{ secrets.SYNC_TOKEN }}@github.com/seuchicoprojetos-sys/seuchicobotequim-cardapio.git
          git push --force --prune mirror refs/remotes/origin/master:refs/heads/master